export const ROUTES = {
    LOGIN: "/login",
    REGISTER: "/register",
    HOME: "/",
    USER_HOME: "/user-home",
    HR_HOME: "/hr-home",
    CVMANAGEMENT: "/user/my-cv",
    CREATENAMECV: "/user/my-cv/template",
    CREATECVPAGE: "/user/my-cv/create",
    DETAILCV: "/user/my-cv/update/:id",
    UPDATECVPAGE: "/user/my-cv/update/:id",
    PROFILE: "/user/profile",
    COMPANIES: "/companies",
    COMPANY_DETAIL: "/companies/:id",
    JOBS: "/jobs",
    JOB_DETAIL: "/jobs/:id",
    APPLICATIONS: "/user/applications",
    HR_APPLICATIONS: "/hr/applications",
    HR_APPLICATION_DETAIL: "/hr/applications/:id",
    HR_JOBS: "/hr/jobs",
    HR_JOB_DETAIL: "/hr/jobs/:id",
    CV_EVALUATE: "/hr/cv-evaluate/:jobId",
    JOBMANAGEMENT: "/hr/jobs",
    APPLICATIONSMANAGEMENT: "/hr/applications",
    CVMATCHING: "/hr/cv-evaluate",
    JOB_APPLICATIONS_DETAIL: "/hr/job-applications/:jobId",    SAVED_CVS: "/hr/saved-cv",
    RECOMMENDED_JOBS: "/user/recommended-jobs",
};
